---

- hosts: 127.0.0.1
  connection: local
  
  vars_files:
    - "defaults/main.yml"

  tasks:
    - include: tasks/set-role-variables.yml
    - name: fetch .tar.gz files from Elastic site
      include: tasks/fetch.yml
      vars:
        sonar_download_from_remote: true
        


  


